name: Increment Semantic Version
description: Bump a given semantic version by a release type ( major | feature | bug | alpha | beta | rc ).
author: Martin Beentjes
branding:
  icon: 'tag'
  color: 'green'
inputs:
  current-version:
    description: 'The current semantic version you want to increment'
    required: true
  version-fragment:
    description: 'The versions fragment you want to increment. possible options are [ major | minor | patch | prerelease ]'
    required: true
outputs:
  next-version:
    description: 'The incremented version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.current-version }}
    - ${{ inputs.version-fragment }}
